version: "3.5"

services:
  angular:
    build: .
    container_name: angular
    #restart: always
    volumes: # Volume binding
        - './docker_angular:/usr/src/app' 
    #env_file: .env
    ports:
      - '3200:3200'
      # ip para ejecutar la app desde el navegador con docker
      # opcion de indicar aquí la url
    #command: >       
    #    bash -c "npm install && ng serve --host 0.0.0.0 --port 3200"      
    networks:
      - angular-nginx-networks
 
  nginx:
    image: nginx:1.19
    container_name: nginx
    #env_file: .env
    restart: always
    ports:
      - "252:80"
    # - "443:443"
    volumes:
      - .nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      #- "${LOG_PATH}:/var/log/nginx"
      #- /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - angular
    networks:
      - angular-nginx-networks
 
networks:
    angular-nginx-networks:
 